bootstrap.servers=uuuu.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='KEY' password='SECRET';
sasl.mechanism=PLAIN
# Required for correctness in Apache Kafka clients prior to 2.6
client.dns.lookup=use_all_dns_ips

# Best practice for higher availability in Apache Kafka clients prior to 3.0
session.timeout.ms=45000

# Best practice for Kafka producer to prevent data loss
acks=all

schema.registry.url=https://xxxx.confluent.cloud
basic.auth.credentials.source=USER_INFO
schema.registry.basic.auth.user.info=SR_KEY:SR_SECRET

use.latest.version=true
auto.register.schemas=false

topic=customers

# These rules are used for CSFLE configuration with kek not shared with Confluent Cloud
rule.executors._default_.param.tenant.id=qqqq
rule.executors._default_.param.client.id=mmmm
rule.executors._default_.param.client.secret=nnnn


